# Generated by Django 2.0.1 on 2019-02-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190201_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product',
            new_name='project',
        ),
    ]
