# Generated by Django 2.0.1 on 2019-02-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190206_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('General', 'General'), ('Sketchbook', 'Sketchbook'), ('Exhibition', 'Exhibition'), ('Teaching', 'Teaching')], default='General', max_length=13),
        ),
    ]
