# Generated by Django 2.0.1 on 2019-02-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190206_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='This will be the thumbnail for the project', null=True, upload_to='main/images/thumbnails/'),
        ),
    ]
