# Generated by Django 2.0.1 on 2019-02-14 13:44

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190213_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='low_res_picture',
            field=models.ImageField(blank=True, help_text='Please provide an low res version of the picture', null=True, upload_to=main.models.get_low_res_image_filename, verbose_name='Low Res Picture'),
        ),
    ]
